import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';
import styles from './layout.module.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
  modal: ReactNode;
};

export default function RootLayout({ children, modal }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.container}>
          <header className={styles.headerWrapper}>
            <div className={styles.headerTop}>
              <Link href="/">
                <h1>GROOVE</h1>
              </Link>
              <input />
              <Link href="/login">로그인</Link>
            </div>
            <div className={styles.headerBottom}>
              <nav>
                <ul>
                  <li>커뮤니티</li>
                  <li>구인구직</li>
                </ul>
              </nav>
            </div>
          </header>
          <hr />
          <div className={styles.mainWrapper}>
            {children}
            {modal}
          </div>
        </div>
      </body>
    </html>
  );
}
